Pull request da semana 10
gui-lirasilva/CodingSchool pull request #10
Opened 2022-04-16 20:42 UTC by gui-lirasilva

2022-04-20 21:21 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/controller/CourseController.java
> +        SubcategoryDTO subcategoryDto = new SubcategoryDTO(subcategory);
Talvez um service pra fazer isso não seria melhor?? Só pra pensar, essa parte verbosa ficaria lá e também seria mais fácil testar

2022-04-20 21:21 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/dto/login/CategoryLoginDTO.java
> +    }
Acho que poderia usar projection aqui, seria bem legal, dá uma olhada nesse projetinho que fiz rápidão como exemplo desse uso: https://github.com/jonilsonds9/spring-data-projections-with-list

2022-04-20 21:21 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/dto/login/SubcategoryLoginDTO.java
> +    private Category category;
Esse cara é usado apenas no Login? Me perdi no nome aqui, porque se for, acho que a projection resolve, se não muda o nome pra fazer mais sentido sabe

2022-04-20 21:21 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/model/access/Profile.java
> +public class Profile implements GrantedAuthority {
Precisa mesmo desse cara???

2022-04-25 18:22 UTC, jonilsonds9 requested changes

2022-04-25 18:22 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/controller/CategoryController.java
> +        CategoryProjectionView categoryProjectionView = categoryService.categoryProjectionByCode(categoryCode);
Deveria ser um Optional aqui não ?

2022-04-25 19:04 UTC, jonilsonds9 approved these changes

2022-04-25 20:32 UTC, fabiuhp approved these changes

2022-04-25 20:35 UTC, merged