Pull request da semana 11
gui-lirasilva/CodingSchool pull request #11
Opened 2022-04-27 19:31 UTC by gui-lirasilva

2022-05-04 17:30 UTC, jonilsonds9 requested changes

2022-05-04 17:30 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/repository/CategoryRepository.java
> +    void removeAll();
Acho que não precisa desse cara

2022-05-04 17:30 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/CoddingSchoolApplicationTest.java
> +    }
Acho que esse cara também não precisa!

2022-05-04 17:30 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/controller/CategoryApiControllerTest.java
> +    void categories__shouldBeNotThrowAnyException() {
Arrumar os nomes como falamos no review

2022-05-04 17:30 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/controller/CategoryApiControllerTest.java
> +        assertDoesNotThrow(() -> {
Porque testar se não está lançando exception?

2022-05-04 17:30 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/repository/CourseRepositoryTest.java
> +        assertDoesNotThrow(() -> courseRepository.findInstructorWithMoreCourses());
Não precisa dessa linha

2022-05-04 17:30 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/repository/UserRepositoryTest.java
> +    }
Arrumar esses caras que são Optional

2022-05-04 17:30 UTC, jonilsonds9 commented on system.properties
> +java.runtime.version=17
Porque esse properties?

2022-05-04 18:54 UTC, gui-lirasilva commented on src/main/java/br/com/coddingSchool/repository/CategoryRepository.java
> +    void removeAll();
Deletei. [20995d9](https://github.com/gui-lirasilva/CodingSchool/pull/11/commits/20995d9aa81b42188d81a849cfd737594745d2a0)
Eu tinha criado quando estava pensando em usar pra apagar o banco de dados, mas não cheguei a usar.

2022-05-04 19:00 UTC, jonilsonds9 approved these changes

2022-05-05 18:55 UTC, fabiuhp approved these changes

2022-05-05 19:04 UTC, merged