Pull request da semana 12
gui-lirasilva/CodingSchool pull request #12
Opened 2022-05-05 20:00 UTC by gui-lirasilva

2022-05-11 16:45 UTC, jonilsonds9 requested changes
Só tem esse arquivo vazio `src/main/resources/insert-values-on-database.sql`, acho que deve remover esse cara!

2022-05-11 16:45 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/controller/CategoryController.java
> +    }
Porque não remover isso e usar o lombok aqui?

2022-05-11 16:45 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/controller/CategoryController.java
> +    public String update(@PathVariable String code, CategoryFormDTO categoryFormDTO, Model model) {
Se tivesse deixado os dois formulario, tipo, um form pra salvar e outro pra alterar, você teria 2 validators mais simples e com apenas 2 if em cada

2022-05-11 16:45 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/controller/CategoryController.java
> +    public String update(@PathVariable String code, CategoryFormDTO categoryFormDTO, Model model) {
não precisa mudar!

2022-05-11 16:45 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/controller/CourseController.java
> +    }
Mesma coisa do outro, acho que com o lombok, você pode remover esse construtor que só enche o código

2022-05-11 16:45 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/dto/form/CategoryFormDTO.java
> +@Setter
Precisa mesmo de todos os setters aqui? Se sim, então beleza, se não, então remove essa anotação e coloca na mão apenas os que você precisa!

2022-05-11 16:45 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/dto/login/CategoryLoginDTO.java
>  public class CategoryLoginDTO {
[Não precisa mudar] Aqui você poderia ter usado os records e ai não teria uma class e nem essa a anotação e ainda assim fazer o stream que você precisa no construtor

2022-05-11 16:45 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/tags/templates/admin-template.tag
> +</html>
Aquilo que falei, poderia fazer um `htmlStart.tag` e um `htmlEnd.tag`, assim ficaria muito mais simples de montar as JSP, acho que vale a pena mudar aqui!

2022-05-11 21:17 UTC, jonilsonds9 requested changes

2022-05-11 21:17 UTC, jonilsonds9 commented on src/main/webapp/WEB-INF/tags/templates/finish-template.tag
> +        <script src="/assets/js/scripts.js"></script>
Acho que esse script não precisa está aqui, o Jquery tudo bem ficar global, mas o script, seria ideial só ser colocado nas paginas que realmente precisam dele, acho que você pode colocar um `doBody` aqui e nas JSP passar esse script, se precisar

2022-05-11 21:38 UTC, jonilsonds9 approved these changes

2022-05-11 21:39 UTC, gui-lirasilva commented on src/main/webapp/WEB-INF/tags/templates/finish-template.tag
> +        <script src="/assets/js/scripts.js"></script>
Feito! [0c520cf](https://github.com/gui-lirasilva/CodingSchool/pull/12/commits/0c520cf6b7e114e25576843053421c61bf26e78b)

2022-05-13 15:25 UTC, fabiuhp approved these changes

2022-05-13 16:19 UTC, merged