Pull request da semana 5
gui-lirasilva/CodingSchool pull request #5
Opened 2022-03-10 21:09 UTC by gui-lirasilva

2022-03-16 16:11 UTC, jonilsonds9 requested changes

2022-03-16 16:11 UTC, jonilsonds9 commented on src/main/java/com/coddingSchool/dao/CourseDao.java
> +            PreparedStatement stmt = connection
Só uma coisa, mais uma padrão, tenta deixar os métodos privados em baixo dos métodos públicos, é uma convensão que agente usa, tipo escreve todos os métodos públicos primeiro e depois todos os privados, porque os público são os que importa pra quem vê de fora sabe

2022-03-16 16:11 UTC, jonilsonds9 commented on src/main/java/com/coddingSchool/run/sql/RunningCourseDelete.java
> +    }
Você tem o mesmo método lá no CourseDAO, acho seria melhor manter apenas o do DAO

2022-03-16 16:11 UTC, jonilsonds9 commented on src/main/java/com/coddingSchool/run/sql/RunningSqlReport.java
> +       try(PreparedStatement stmt = connection.prepareStatement("SELECT `name` FROM subcategory WHERE `id` = ?")){
Adicionar espaço: ` WHERE `id` = ?")) {`

2022-03-16 16:11 UTC, jonilsonds9 commented on src/main/resources/db/migration/V6__advanced-querys.sql
> +group by ca.`name`;
Colocar os alias (`as`) corretamente

2022-03-16 16:11 UTC, jonilsonds9 commented on target/classes/db/migration/V5__select-values-in-tables.sql
> +SELECT `name` FROM `subcategories` where `description` = '';
Esse arquivo tá repetido ou eu tô vendo errado?

2022-03-16 16:11 UTC, jonilsonds9 commented on target/classes/db/migration/V6__advanced-querys.sql
> +group by ca.`name`;
Mesma coisa do outro, tá repetido ou eu é que tô bugado?

2022-03-16 16:53 UTC, gui-lirasilva commented on src/main/java/com/coddingSchool/dao/CourseDao.java
> +            PreparedStatement stmt = connection
Feito! [df7372d](https://github.com/gui-lirasilva/CodingSchool/pull/5/commits/df7372d508ebedc1ae1dcd2c5d4ee6a7294b341c)

2022-03-16 16:54 UTC, gui-lirasilva commented on src/main/java/com/coddingSchool/run/sql/RunningCourseDelete.java
> +    }
Feito! [df7372d](https://github.com/gui-lirasilva/CodingSchool/pull/5/commits/df7372d508ebedc1ae1dcd2c5d4ee6a7294b341c)
E aproveitei pra colocar a classe que fazia o `Update` pra DAO.

2022-03-16 16:57 UTC, gui-lirasilva commented on src/main/java/com/coddingSchool/run/sql/RunningSqlReport.java
> +       try(PreparedStatement stmt = connection.prepareStatement("SELECT `name` FROM subcategory WHERE `id` = ?")){
Feito! [e5b5b83](https://github.com/gui-lirasilva/CodingSchool/pull/5/commits/e5b5b83480f909a3a142dd0a019e776cbd49c8f0)

2022-03-16 16:58 UTC, gui-lirasilva commented on src/main/resources/db/migration/V6__advanced-querys.sql
> +group by ca.`name`;
Feito! [df7372d](https://github.com/gui-lirasilva/CodingSchool/pull/5/commits/df7372d508ebedc1ae1dcd2c5d4ee6a7294b341c)

2022-03-16 16:59 UTC, gui-lirasilva commented on target/classes/db/migration/V5__select-values-in-tables.sql
> +SELECT `name` FROM `subcategories` where `description` = '';
Acho que foi só aí, aqui só tem um mesmo

2022-03-16 16:59 UTC, gui-lirasilva commented on target/classes/db/migration/V6__advanced-querys.sql
> +group by ca.`name`;
Aqui só tem um mesmo

2022-03-16 17:01 UTC, jonilsonds9 requested changes

2022-03-16 17:01 UTC, jonilsonds9 commented on src/main/java/com/coddingSchool/dao/CourseDao.java
> +    public static void updateCourse() {
Acho que deveria indicar que vai atuerar todos os cursos não?

2022-03-16 17:02 UTC, jonilsonds9 commented on src/main/java/com/coddingSchool/dao/CourseDao.java
> +    public static void updateCourse() {
tipo `updateAllCourses`

2022-03-16 17:03 UTC, gui-lirasilva commented on src/main/java/com/coddingSchool/dao/CourseDao.java
> +    public static void updateCourse() {
`updateAllCourses` ficaria melhor?

2022-03-16 17:08 UTC, gui-lirasilva commented on src/main/java/com/coddingSchool/dao/CourseDao.java
> +    public static void updateCourse() {
Feito! [b273fa3](https://github.com/gui-lirasilva/CodingSchool/pull/5/commits/b273fa33f1abc8cc6adc33366656224438800667)

2022-03-16 17:08 UTC, jonilsonds9 approved these changes

2022-03-17 11:21 UTC, fabiuhp approved these changes

2022-03-17 14:51 UTC, merged