Pull request semana 6
gui-lirasilva/CodingSchool pull request #6
Opened 2022-03-17 16:18 UTC by gui-lirasilva

2022-03-23 18:15 UTC, jonilsonds9 requested changes
Alguns pontos de atenção!

- Antes de fazer o commit, sempre verificar os arquivos que você mudou e quais foram as mudanças, pra evitar de subir coisas que não deveriam, rodar um `git diff` antes de fazer um commit ou ver pelo Intellij.
- Ver a questão de ter várias classes com `main` para testar coisas individualmente.

2022-03-23 18:15 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/model/Explanation.java
> +public class Explanation extends Activity{
Adicionar espaço `Activity {`

2022-03-23 18:15 UTC, jonilsonds9 commented on src/main/java/br/com/coddingSchool/run/sql/RunningDao.java
> +
O que eu falei mais cedo no review, tentar separar em várias classes com metodo `main` pra evitar esses comentários e dificuldade de testar as coisas sabe

2022-03-23 18:15 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/dao/CategoryDaoTest.java
> +    }
Sobe esse cara pra cima dos métodos de testes, vendo que ele é usado em todos, assim facilita na manutenção do código, de cara quem vê, sabe que tem essa ação que executa depois de todos os testes.

2022-03-23 18:15 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/dao/CourseDaoTest.java
> +    }
Mesma coisa aqui

2022-03-23 18:15 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/model/CategoryTest.java
> +//
Porque comentou isso? Volta esses caras e vê se todos os testes passam

2022-03-23 18:15 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/model/CourseTest.java
> +//    }
Mesma coisa que falei no outro, não sei o motivo, mas os testes precisam estar sempre pronto, pensa que esse projeto tivesse um build pra ver se todos os testes estão passando antes do código ir pra produção?

2022-03-23 18:15 UTC, jonilsonds9 commented on src/test/java/br/com/coddingSchool/model/SubcategoryTest.java
> +//    }
Mesma coisa, descomenta e vê se continua passando os testes

2022-03-23 18:15 UTC, jonilsonds9 commented on target/classes/META-INF/persistence.xml
> +</persistence>
Veio coisas que não deveria! Tudo dentro de target não pode vir pro GitHub

2022-03-23 18:15 UTC, jonilsonds9 commented on target/classes/db/migration/V1__create-database-and-tables.sql
> -  `name` varchar(100) not null,
Também do target

2022-03-23 18:15 UTC, jonilsonds9 commented on target/classes/db/migration/V2__insert-values-on-table-category.sql
> -INSERT INTO categories VALUES(
Também do target, tem que remover!

2022-03-23 19:26 UTC, gui-lirasilva commented on src/main/java/br/com/coddingSchool/model/Explanation.java
> +public class Explanation extends Activity{
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)

2022-03-23 19:26 UTC, gui-lirasilva commented on src/main/java/br/com/coddingSchool/run/sql/RunningDao.java
> +
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)

2022-03-23 19:27 UTC, gui-lirasilva commented on src/test/java/br/com/coddingSchool/dao/CategoryDaoTest.java
> +    }
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)

2022-03-23 19:36 UTC, gui-lirasilva commented on src/test/java/br/com/coddingSchool/dao/CourseDaoTest.java
> +    }
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)

2022-03-23 19:36 UTC, gui-lirasilva commented on src/test/java/br/com/coddingSchool/model/CategoryTest.java
> +//
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)
Tirei os comentários e coloquei os elementos que faltavam pra os testes voltarem a funcionar

2022-03-23 19:37 UTC, gui-lirasilva commented on src/test/java/br/com/coddingSchool/model/CourseTest.java
> +//    }
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)

2022-03-23 19:37 UTC, gui-lirasilva commented on src/test/java/br/com/coddingSchool/model/SubcategoryTest.java
> +//    }
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)

2022-03-23 19:37 UTC, gui-lirasilva commented on target/classes/META-INF/persistence.xml
> +</persistence>
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)
Coloquei a `target` no gitignore e removi daqui

2022-03-23 19:37 UTC, gui-lirasilva commented on target/classes/db/migration/V1__create-database-and-tables.sql
> -  `name` varchar(100) not null,
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)

2022-03-23 19:38 UTC, gui-lirasilva commented on target/classes/db/migration/V2__insert-values-on-table-category.sql
> -INSERT INTO categories VALUES(
Feito! [088418c](https://github.com/gui-lirasilva/CodingSchool/pull/6/commits/088418c6b0d89d92e51db852f2581f0379b57f20)

2022-03-23 20:31 UTC, jonilsonds9 approved these changes

2022-03-24 12:13 UTC, fabiuhp approved these changes

2022-03-24 15:43 UTC, merged